package modelo;

public enum Cambios {
    LISTOPARAINICIAR, LISTAJUGADORESACTUALIZADA, INICIOLAPARTIDA, CONSULTARSIACEPTAENVIDO, SETERMINOELENVIDO, RONDATERMINADA, CONSULTARSIACEPTATRUCO, CONSULTARENVIDOTRASTRUCO, DESAROLLOCARTAS, CONSULTARENVIDO, SEGUIJUGANDO, NOTIFICARESTADOENVIO, NOTIFICARESTADOTRUCO;

}
